services:
  - type: web
    name: countdown-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    region: frankfurt
    plan: free
    build:
      aptPackages:
        - libcairo2-dev
        - libpango1.0-dev
        - libjpeg-dev
        - libgif-dev
        - librsvg2-dev
